### ISSUE TITLE
Error attempting to run

### ISSUE THREAD

**Issue by gregsdennis** [inadarei/json-compact-formatter#3]
I'm getting this anytime I attempt to run the command.  I just installed it.

![image](https://user-images.githubusercontent.com/2676804/181122854-a992d20b-7286-4e5a-9b26-ec6c8e2f15d6.png)

VSCode Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by inadarei** [comment]
Thank you for reporting. Will look into the issue.

**Comment by fmg-lydonchandra** [comment]
getting same issue, had to revert to previous version

**Comment by inadarei** [comment]
Ok, I fixed couple things and rewrote in Typescript. It seems to work well now. The version that should be the best is 1.3.9

Can somebody verify, please?

Thank you

**Comment by fmg-lydonchandra** [comment]
Confirmed fixed with v1.3.9, I also had to update VSCode to the latest version, otherwise can only install v1.3.7, not sure why.

**Comment by inadarei** [comment]
@fmg-lydonchandra thank you for testing. And sorry you had to update VS Code. I tried to fix that forced update in 1.3.10, so it tolerates fairly older VS Codes
